title: "Chris Rawles"
description: "Staff Research Engineer at Google DeepMind"
baseurl: ""
url: "https://crawles.github.io"
permalink: /:title/
encoding: utf-8
markdown: kramdown

author:
  name: Chris Rawles
  title: Staff Research Engineer, Google DeepMind
  github: crawles
  twitter: thecrawles
  linkedin: chris-rawles-50854826
  scholar: "https://scholar.google.com/citations?user=wINI4kcAAAAJ&hl=en"
